// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pntt_231220952.Models;

#nullable disable

namespace pntt_231220952.Migrations
{
    [DbContext(typeof(pnttDBContext))]
    partial class pnttDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pntt_231220952.Models.PnttComputer", b =>
                {
                    b.Property<int>("PnttComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PnttComId"));

                    b.Property<string>("PnttComImage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PnttComName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("PnttComPrice")
                        .HasColumnType("float");

                    b.Property<bool>("PnttComStatus")
                        .HasColumnType("bit");

                    b.HasKey("PnttComId");

                    b.ToTable("pnttComputer");
                });
#pragma warning restore 612, 618
        }
    }
}
